import { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Banknote, CreditCard, Download, RefreshCw, ShieldCheck, TrendingUp, Users } from 'lucide-react';
import api from '../config/api';
import { Button, ConfirmDialog, Dialog, TextField } from '../design-system';

type Metrics = { activeSubscriptions: number; activeTrials: number; expiredTrials: number; mrr: number; arr: number; totalRevenue: number; grossRevenue: number; refunds: number; netCollectedRevenue: number; revenue30Days: number; grossRevenue30Days: number; refunds30Days: number; netRevenue30Days: number; estimatedTransactionFees: number; estimatedNetRevenue: number; grossMarginPercent: number; trialConversionPercent: number; monthlyCancellationRate: number };
type Summary = { plans: Record<string, number>; statuses: Record<string, number>; payments: Record<string, number>; delivery: { statuses: Record<string, number>; types: Record<string, number>; total: number; deliveryRatePercent: number }; metrics: Metrics; capacityWarnings: Array<{ organizationId: string; organizationName: string; plan: string; members: number; limit: number; percentage: number }> };
type Subscription = { id: string; plan: string; status: string; billingCycle: string; trialEndsAt?: string | null; currentPeriodEnd?: string | null; memberCount: number; memberLimit: number | null; organization: { id: string; name: string; slug: string } };
type Payment = { id: string; requestedPlan: string; billingCycle: string; amount: string; status: string; paidAt?: string | null; createdAt: string; receiptNumber?: string | null; organization?: { name: string } | null; user: { firstName: string; lastName: string; email: string }; billingDocuments: Array<{ id: string; type: string; documentNumber: string; status: string }> };
type Readiness = { checks: Record<string, boolean>; demoPaymentAvailable: boolean; productionReady: boolean; message: string };
type CustomRequest = { id: string; contactName: string; contactEmail: string; contactPhone?: string | null; estimatedMembers?: number | null; requirements: string; preferredTimeline?: string | null; status: string; createdAt: string; organization: { id: string; name: string } };
const plans = ['FREE', 'STARTER', 'GROWTH', 'PRO', 'INVESTMENT_AUTOMATION', 'ENTERPRISE'];
const money = (value: number) => `KES ${Math.round(value).toLocaleString()}`;

export const PlatformSubscriptions = () => {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [items, setItems] = useState<Subscription[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [search, setSearch] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const [draftPlans, setDraftPlans] = useState<Record<string, string>>({});
  const [readiness, setReadiness] = useState<Readiness | null>(null);
  const [customRequests, setCustomRequests] = useState<CustomRequest[]>([]);
  const [manualPaymentItem, setManualPaymentItem] = useState<Subscription | null>(null);
  const [manualReference, setManualReference] = useState('');
  const [refundPayment, setRefundPayment] = useState<Payment | null>(null);
  const [refundReason, setRefundReason] = useState('');
  const [refundReference, setRefundReference] = useState('');
  const [simulationPayment, setSimulationPayment] = useState<Payment | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const [summaryResponse, listResponse, paymentResponse, readinessResponse, customResponse] = await Promise.all([
        api.get('/platform/subscriptions/summary'),
        api.get('/platform/subscriptions', { params: { search: search || undefined } }),
        api.get('/platform/subscriptions/payments', { params: { limit: 10 } }),
        api.get('/platform/subscriptions/readiness'),
        api.get('/platform/subscriptions/custom-requests'),
      ]);
      setSummary(summaryResponse.data); setItems(listResponse.data.items); setPayments(paymentResponse.data.items); setReadiness(readinessResponse.data); setCustomRequests(customResponse.data.items);
    } catch (requestError: any) { setError(requestError?.response?.data?.error?.message || 'Unable to load platform billing.'); }
    finally { setLoading(false); }
  }, [search]);

  useEffect(() => { void load(); }, [load]);
  const update = async (id: string, data: Record<string, unknown>) => {
    setLoading(true); setError(''); setMessage('');
    try { const response = await api.patch(`/platform/subscriptions/${id}`, data); setMessage(response.data.message); await load(); }
    catch (requestError: any) { setError(requestError?.response?.data?.error?.message || 'Unable to update the subscription.'); setLoading(false); }
  };
  const recordManualPayment = async () => {
    const item = manualPaymentItem;
    if (!item || !manualReference.trim()) return;
    const plan = draftPlans[item.id] || (item.plan === 'FREE' ? 'STARTER' : item.plan);
    if (plan === 'FREE') { setError('Select a paid plan before recording a payment.'); return; }
    setLoading(true); setError('');
    try { const response = await api.post(`/platform/subscriptions/${item.id}/manual-payment`, { plan, billingCycle: item.billingCycle || 'MONTHLY', reference: manualReference.trim() }); setMessage(response.data.message); setManualPaymentItem(null); setManualReference(''); await load(); }
    catch (requestError: any) { setError(requestError?.response?.data?.error?.message || 'Unable to record the manual payment.'); setLoading(false); }
  };
  const metrics = summary?.metrics;
  const exportReconciliation = async () => { const response = await api.get('/platform/subscriptions/reconciliation.csv', { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `CHAMA360-billing-reconciliation-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  const downloadPlatformDocument = async (id: string, name: string) => { const response = await api.get(`/platform/subscriptions/billing-documents/${id}/pdf`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `${name}.pdf`; link.click(); URL.revokeObjectURL(url); };
  const recordRefund = async () => { const payment = refundPayment; if (!payment || !refundReason.trim() || !refundReference.trim()) return; setLoading(true); setError(''); try { const response = await api.post(`/platform/subscriptions/payments/${payment.id}/refund`, { reason: refundReason.trim(), refundReference: refundReference.trim() }); setMessage(response.data.message); setRefundPayment(null); setRefundReason(''); setRefundReference(''); await downloadPlatformDocument(response.data.creditNote.id, response.data.creditNote.documentNumber); await load(); } catch (requestError: any) { setError(requestError?.response?.data?.error?.message || 'Unable to record the refund.'); setLoading(false); } };
  const simulatePayment = async () => { const payment = simulationPayment; if (!payment) return; setLoading(true); setError(''); try { const response = await api.post(`/platform/subscriptions/payments/${payment.id}/simulate-success`); setMessage(response.data.message); setSimulationPayment(null); await load(); } catch (requestError: any) { setError(requestError?.response?.data?.error?.message || 'Unable to simulate the payment.'); setLoading(false); } };
  const updateCustomRequest = async (id: string, status: string) => { setLoading(true); try { const response = await api.patch(`/platform/subscriptions/custom-requests/${id}`, { status }); setMessage(response.data.message); await load(); } catch (requestError: any) { setError(requestError?.response?.data?.error?.message || 'Unable to update the custom request.'); setLoading(false); } };

  return <div className="subscription-page platform-revenue-page">
    <section className="subscription-hero"><span><ShieldCheck /> Restricted CHAMA360 operations</span><h1>Revenue & subscriptions</h1><p>Track recurring revenue, conversion, payment health, estimated transaction costs, and chama capacity from one control centre.</p><button className="revenue-export-button" type="button" onClick={() => void exportReconciliation()}><Download/> Export reconciliation</button></section>
    {error ? <div className="error-banner px-4 py-3 text-sm">{error}</div> : null}{message ? <div className="success-banner px-4 py-3 text-sm">{message}</div> : null}
    {readiness ? <section className={`provider-readiness ${readiness.productionReady ? 'is-ready' : ''}`}><div><ShieldCheck/><span><strong>{readiness.productionReady ? 'Production providers ready' : 'Development flow ready'}</strong><small>{readiness.message}</small></span></div><ul>{Object.entries(readiness.checks).map(([name, ready]) => <li key={name} className={ready ? 'is-ready' : ''}><i>{ready ? '✓' : '!'}</i>{name.replace(/([A-Z])/g, ' $1')}</li>)}</ul></section> : null}
    <section className="revenue-kpi-grid">
      {[
        ['Monthly recurring revenue', money(metrics?.mrr ?? 0), TrendingUp, 'Projected from active monthly and annual plans'],
        ['Annual recurring revenue', money(metrics?.arr ?? 0), Banknote, 'Current run-rate'],
        ['Gross collections', money(metrics?.grossRevenue ?? 0), CreditCard, 'All completed subscription payments'],
        ['Recorded refunds', money(metrics?.refunds ?? 0), ArrowDownRight, 'Confirmed credit notes deducted from revenue'],
        ['Net collected revenue', money(metrics?.netCollectedRevenue ?? 0), ArrowUpRight, 'Gross collections less confirmed refunds'],
        ['Net after payment fees', money(metrics?.estimatedNetRevenue ?? 0), Banknote, `After ${money(metrics?.estimatedTransactionFees ?? 0)} estimated M-Pesa fees`],
        ['Estimated retained margin', `${metrics?.grossMarginPercent ?? 0}%`, Activity, 'After refunds and payment fees; operating costs excluded'],
        ['Active paid chamas', metrics?.activeSubscriptions ?? 0, Users, `${metrics?.activeTrials ?? 0} active trials`],
        ['Trial conversion', `${metrics?.trialConversionPercent ?? 0}%`, ArrowUpRight, `${metrics?.expiredTrials ?? 0} expired trials`],
        ['30-day net collections', money(metrics?.netRevenue30Days ?? metrics?.revenue30Days ?? 0), CreditCard, `${money(metrics?.grossRevenue30Days ?? 0)} gross · ${money(metrics?.refunds30Days ?? 0)} refunded`],
        ['Monthly cancellations', `${metrics?.monthlyCancellationRate ?? 0}%`, ArrowDownRight, `${summary?.statuses.PAST_DUE ?? 0} past due`],
        ['Message delivery', `${summary?.delivery.deliveryRatePercent ?? 0}%`, Activity, `${summary?.delivery.statuses.DELIVERED ?? 0} delivered · ${summary?.delivery.statuses.FAILED ?? 0} failed in 30 days`],
      ].map(([label, value, Icon, note]: any) => <article className="dashboard-tile revenue-kpi" key={label}><Icon/><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}
    </section>
    <section className="grid gap-4 lg:grid-cols-2">
      <div className="section-shell"><div className="section-header"><p className="text-sm text-[var(--ds-text-muted)]">Commercial mix</p><h2 className="text-xl font-black text-[var(--ds-secondary)]">Chamas by plan</h2></div><div className="section-body plan-mix">{plans.map((plan) => <div key={plan}><span>{plan}</span><strong>{summary?.plans[plan] ?? 0}</strong><i style={{ width: `${Math.min(100, ((summary?.plans[plan] ?? 0) / Math.max(1, Object.values(summary?.plans ?? {}).reduce((a, b) => a + b, 0))) * 100)}%` }} /></div>)}</div></div>
      <div className="section-shell"><div className="section-header"><p className="text-sm text-[var(--ds-text-muted)]">Upgrade opportunities</p><h2 className="text-xl font-black text-[var(--ds-secondary)]">Capacity warnings</h2></div><div className="section-body capacity-list">{summary?.capacityWarnings.map((warning) => <div key={warning.organizationId}><AlertTriangle/><span><strong>{warning.organizationName}</strong><small>{warning.members} of {warning.limit} members · {warning.plan}</small></span><b>{warning.percentage}%</b></div>)}{!summary?.capacityWarnings.length ? <p className="empty-copy">No chamas are currently approaching their member limit.</p> : null}</div></div>
    </section>
    <section className="section-shell overflow-hidden"><div className="section-header"><p className="text-sm text-[var(--ds-text-muted)]">Tailored packages</p><h2 className="text-xl font-black text-[var(--ds-secondary)]">Custom organization requests</h2></div><div className="section-body space-y-3">{customRequests.map((request) => <article className="dashboard-tile p-4" key={request.id}><div className="flex flex-wrap items-start justify-between gap-3"><span><strong>{request.organization.name}</strong><small className="block text-[var(--ds-text-muted)]">{request.contactName} · {request.contactEmail}{request.contactPhone ? ` · ${request.contactPhone}` : ''}</small></span><select className="input compact-input" value={request.status} disabled={loading} onChange={(event) => void updateCustomRequest(request.id, event.target.value)}>{['SUBMITTED', 'REVIEWING', 'CONTACTED', 'QUOTED', 'ACCEPTED', 'DECLINED', 'CLOSED'].map((status) => <option key={status}>{status}</option>)}</select></div><p className="mt-3 whitespace-pre-wrap text-sm">{request.requirements}</p><small className="mt-3 block text-[var(--ds-text-muted)]">{request.estimatedMembers ? `${request.estimatedMembers.toLocaleString()} estimated members · ` : ''}{request.preferredTimeline || 'Timeline not specified'} · Submitted {new Date(request.createdAt).toLocaleDateString()}</small></article>)}{!loading && !customRequests.length ? <p className="empty-copy">No custom package requests have been submitted.</p> : null}</div></section>
    <section className="section-shell overflow-hidden"><div className="section-header flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-[var(--ds-text-muted)]">Organization billing</p><h2 className="text-xl font-black text-[var(--ds-secondary)]">Chama subscriptions</h2></div><div className="flex gap-2"><label className="sr-only" htmlFor="subscription-search">Search chamas</label><input id="subscription-search" className="input" placeholder="Search chama" value={search} onChange={(event) => setSearch(event.target.value)} /><button className="btn btn-outline" onClick={() => void load()} disabled={loading}><RefreshCw className="h-4 w-4"/> Refresh</button></div></div>
      <div className="section-body overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Chama</th><th className="p-3">Members</th><th className="p-3">Plan</th><th className="p-3">Status</th><th className="p-3">Paid through</th><th className="p-3">Controls</th></tr></thead><tbody>{items.map((item) => <tr className="border-b" key={item.id}><td className="p-3"><strong>{item.organization.name}</strong><small className="block text-[var(--ds-text-muted)]">{item.organization.slug}</small></td><td className="p-3">{item.memberCount}{item.memberLimit ? ` / ${item.memberLimit}` : ''}</td><td className="p-3"><select aria-label={`Plan for ${item.organization.name}`} className="input compact-input" value={draftPlans[item.id] ?? item.plan} onChange={(event) => setDraftPlans((current) => ({ ...current, [item.id]: event.target.value }))}>{plans.map((plan) => <option key={plan}>{plan}</option>)}</select></td><td className="p-3"><span className={`billing-status status-${item.status.toLowerCase()}`}>{item.status}</span></td><td className="p-3">{item.currentPeriodEnd ? new Date(item.currentPeriodEnd).toLocaleDateString() : item.trialEndsAt ? `Trial: ${new Date(item.trialEndsAt).toLocaleDateString()}` : '—'}</td><td className="p-3"><div className="billing-actions"><button disabled={loading || (draftPlans[item.id] ?? item.plan) === item.plan} onClick={() => void update(item.id, { plan: draftPlans[item.id] })}>Apply plan</button>{item.plan === 'FREE' ? <button disabled={loading} onClick={() => void update(item.id, { extendTrialDays: 7 })}>+7 trial days</button> : null}<button disabled={loading} onClick={() => void update(item.id, { status: item.status === 'CANCELLED' ? 'ACTIVE' : 'CANCELLED' })}>{item.status === 'CANCELLED' ? 'Reactivate' : 'Suspend'}</button><button disabled={loading} onClick={() => { setManualPaymentItem(item); setManualReference(''); }}>Manual payment</button></div></td></tr>)}</tbody></table>{!loading && !items.length ? <p className="p-5 text-center text-[var(--ds-text-muted)]">No subscriptions match this search.</p> : null}</div>
    </section>
    <section className="section-shell overflow-hidden"><div className="section-header"><p className="text-sm text-[var(--ds-text-muted)]">Latest checkout activity</p><h2 className="text-xl font-black text-[var(--ds-secondary)]">Payments</h2></div><div className="section-body overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Chama</th><th className="p-3">Plan</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Date</th><th className="p-3">Reference</th><th className="p-3">Documents & refund</th></tr></thead><tbody>{payments.map((payment) => { const creditNote = payment.billingDocuments.find((document) => document.type === 'CREDIT_NOTE'); const receipt = payment.billingDocuments.find((document) => document.type === 'RECEIPT'); return <tr className="border-b" key={payment.id}><td className="p-3"><strong>{payment.organization?.name ?? 'Legacy account'}</strong><small className="block text-[var(--ds-text-muted)]">{payment.user.firstName} {payment.user.lastName}</small></td><td className="p-3">{payment.requestedPlan} · {payment.billingCycle}</td><td className="p-3">KES {Number(payment.amount).toLocaleString()}</td><td className="p-3"><span className={`billing-status status-${creditNote ? 'refunded' : payment.status.toLowerCase()}`}>{creditNote ? 'REFUNDED' : payment.status}</span></td><td className="p-3">{new Date(payment.paidAt ?? payment.createdAt).toLocaleDateString()}</td><td className="p-3">{payment.receiptNumber ?? '—'}</td><td className="p-3"><div className="billing-actions">{receipt ? <button onClick={() => void downloadPlatformDocument(receipt.id, receipt.documentNumber)}><Download/> Receipt</button> : null}{creditNote ? <button onClick={() => void downloadPlatformDocument(creditNote.id, creditNote.documentNumber)}><Download/> Credit note</button> : payment.status === 'COMPLETED' ? <button disabled={loading} onClick={() => { setRefundPayment(payment); setRefundReason(''); setRefundReference(''); }}>Record refund</button> : null}</div></td></tr>; })}</tbody></table></div></section>
    {readiness?.demoPaymentAvailable && payments.some((payment) => ['PENDING', 'PROCESSING'].includes(payment.status)) ? <section className="demo-payment-panel"><div><Activity/><span><strong>Development payment simulator</strong><small>Complete an open checkout without contacting M-Pesa or charging a phone.</small></span></div>{payments.filter((payment) => ['PENDING', 'PROCESSING'].includes(payment.status)).map((payment) => <button key={payment.id} disabled={loading} onClick={() => setSimulationPayment(payment)}>Complete {payment.organization?.name ?? payment.requestedPlan} test payment · KES {Number(payment.amount).toLocaleString()}</button>)}</section> : null}
    <Dialog open={Boolean(manualPaymentItem)} title="Record manual payment" description={manualPaymentItem ? `Add a verified receipt for ${manualPaymentItem.organization.name}.` : undefined} onClose={() => { if (!loading) setManualPaymentItem(null); }}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void recordManualPayment(); }}><TextField label="Bank or M-Pesa receipt reference" value={manualReference} onChange={(event) => setManualReference(event.target.value)} required autoFocus /><div className="flex justify-end gap-3"><Button variant="outline" disabled={loading} onClick={() => setManualPaymentItem(null)}>Cancel</Button><Button type="submit" loading={loading}>Record payment</Button></div></form></Dialog>
    <Dialog open={Boolean(refundPayment)} title="Record confirmed refund" description="Enter the approved reason and provider reversal reference. A credit note will be generated." onClose={() => { if (!loading) setRefundPayment(null); }}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void recordRefund(); }}><TextField label="Refund reason" value={refundReason} onChange={(event) => setRefundReason(event.target.value)} required autoFocus /><TextField label="Bank or M-Pesa reversal reference" value={refundReference} onChange={(event) => setRefundReference(event.target.value)} required /><div className="flex justify-end gap-3"><Button variant="outline" disabled={loading} onClick={() => setRefundPayment(null)}>Cancel</Button><Button type="submit" className="ds-button-danger" loading={loading}>Record refund</Button></div></form></Dialog>
    <ConfirmDialog open={Boolean(simulationPayment)} title="Complete test payment?" description={`This development-only action marks ${simulationPayment?.organization?.name ?? 'the selected'} checkout complete without contacting M-Pesa or charging a phone.`} confirmLabel="Complete test payment" busy={loading} onClose={() => setSimulationPayment(null)} onConfirm={() => void simulatePayment()} />
  </div>;
};
