export const ROUTES = {
  auth: {
    splash: "/splash",
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    otpVerification: "/otp-verification",
  },
  app: {
    home: "/dashboard",
    myChamas: "/my-chamas",
    designSystem: "/design-system",
    createChama: "/create-chama",
    joinChama: "/join-chama",
    mobile: "/mobile",
    notifications: "/notifications",
    profile: "/profile",
    upgrade: "/upgrade",
  },
  invitations: {
    join: (shareableLink: string) => `/join/${shareableLink}`,
    organization: (token: string) => `/org-invite/${token}`,
  },
  createChama: {
    type: "/create-chama/type",
    details: "/create-chama/details",
    modules: "/create-chama/modules",
    contributions: "/create-chama/contributions",
    loans: "/create-chama/loans",
    welfare: "/create-chama/welfare",
    committee: "/create-chama/committee",
    invite: "/create-chama/invite",
    review: "/create-chama/review",
  },
  chama: {
    dashboard: (organizationId: string) => `/chamas/${organizationId}/dashboard`,
    members: (organizationId: string) => `/chamas/${organizationId}/members`,
    contributions: (organizationId: string) => `/chamas/${organizationId}/contributions`,
    loans: (organizationId: string) => `/chamas/${organizationId}/loans`,
    loan: (organizationId: string, loanId: string) => `/chamas/${organizationId}/loans/${loanId}`,
    welfare: (organizationId: string) => `/chamas/${organizationId}/welfare`,
    approvals: (organizationId: string) => `/chamas/${organizationId}/approvals`,
    approvalQueue: (organizationId: string, kind: string) => `/chamas/${organizationId}/approvals/${kind}`,
    approvalItem: (organizationId: string, kind: string, itemId: string) => `/chamas/${organizationId}/approvals/${kind}/${itemId}`,
    financialExceptions: (organizationId: string) => `/chamas/${organizationId}/financial-exceptions`,
    investments: (organizationId: string) => `/chamas/${organizationId}/investments`,
    meetings: (organizationId: string) => `/chamas/${organizationId}/meetings`,
    meeting: (organizationId: string, meetingId: string) => `/chamas/${organizationId}/meetings/${meetingId}`,
    voting: (organizationId: string) => `/chamas/${organizationId}/voting`,
    vote: (organizationId: string, voteId: string) => `/chamas/${organizationId}/voting/${voteId}`,
    reports: (organizationId: string) => `/chamas/${organizationId}/reports`,
    documents: (organizationId: string) => `/chamas/${organizationId}/documents`,
    settings: (organizationId: string) => `/chamas/${organizationId}/settings`,
  },
  admin: {
    home: "/admin",
    roles: "/admin/roles",
    approvals: "/admin/approvals",
    wallet: "/admin/wallet",
    auditLogs: "/admin/audit-logs",
    mpesa: "/admin/mpesa",
    chamaSettings: "/admin/chama-settings",
  },
  more: {
    meetings: "/meetings",
    reports: "/reports",
    documents: "/documents",
    voting: "/voting",
    settings: "/settings",
    auditLogs: "/audit-logs",
    help: "/help",
  },
  platform: { home: '/platform', subscriptions: '/platform/subscriptions' },
  legal: { centre: '/legal', download: '/download' },
} as const;
